version: "3"
services:  
  redis:
    command: [ "redis-server", "/redis.conf" ]
    image: "redis:latest"
    expose:
        - "6379"
    volumes:
      - ./config/redis.conf:/redis.conf
    container_name: "redis"

  db:
    image: postgres
    expose:
      - "5432"
    restart: unless-stopped        
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ".env"

  web:    
    env_file:
      - ".env"      
    build: . 
    image: openskiessh/flight-blender
    command: ./entrypoint.sh
    ports:
        - "8000:8000"
    depends_on:
      - redis
      - db      
    volumes:
      - .:/app
      
  celery:
    container_name: flight-blender-worker
    image: openskiessh/flight-blender
    build:
      context: "."        
    env_file:
      - ".env"
    command: celery --app=flight_blender worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
  
  
volumes:
  app:
  db_data: